default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: commenda
  username: root
  password: root

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
